# gen_schema.ps1 - Generate service_c/schema_sql.h from db/schema.sql
#
# This keeps the SQL in ONE place. The C service embeds the schema at compile
# time (so the deployed .exe needs no external .sql file), while db/schema.sql
# stays the authoritative, readable source.
#
# Usage:  powershell -File db\gen_schema.ps1
#
# build.cmd calls this automatically before compiling.

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$RepoRoot  = Split-Path -Parent $ScriptDir
$SrcFile   = Join-Path $ScriptDir "schema.sql"
$DstFile   = Join-Path $RepoRoot "service_c\schema_sql.h"

if (-not (Test-Path $SrcFile)) {
    Write-Error "schema.sql not found: $SrcFile"
    exit 1
}

# Read the SQL and drop comment-only lines (keeps the C string compact while
# leaving the .sql file self-documenting).
$lines = Get-Content -Path $SrcFile -Encoding UTF8 |
         Where-Object { $_ -notmatch '^\s*--' }

# Escape for a C string literal: backslash first, then double quotes.
function ConvertTo-CLiteral([string]$line) {
    $s = $line -replace '\\', '\\'
    $s = $s -replace '"', '\"'
    return $s
}

$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("/*")
[void]$sb.AppendLine(" * schema_sql.h - GENERATED FILE -- DO NOT EDIT")
[void]$sb.AppendLine(" *")
[void]$sb.AppendLine(" * Generated by db\gen_schema.ps1 from db\schema.sql.")
[void]$sb.AppendLine(" * Edit that file and run build.cmd to regenerate.")
[void]$sb.AppendLine(" *")
[void]$sb.AppendLine(" * Contains the embedded DDL for recycle.db. Every statement is")
[void]$sb.AppendLine(" * idempotent so re-running is safe.")
[void]$sb.AppendLine(" */")
[void]$sb.AppendLine("#ifndef _RBSVC_SCHEMA_SQL_H_")
[void]$sb.AppendLine("#define _RBSVC_SCHEMA_SQL_H_")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const char *const kSchema =")

$emitted = 0
foreach ($line in $lines) {
    $trimmed = $line.TrimEnd()
    if ([string]::IsNullOrWhiteSpace($trimmed)) { continue }
    [void]$sb.AppendLine("    `"" + (ConvertTo-CLiteral $trimmed) + "\n`"")
    $emitted++
}

[void]$sb.AppendLine("    ;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif /* _RBSVC_SCHEMA_SQL_H_ */")

# Write without BOM so MSVC parses it cleanly
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($DstFile, $sb.ToString(), $utf8NoBom)

Write-Host "  generated $DstFile ($emitted SQL lines)"
